server:
  port: 8000

zuul:
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  prefix: /api
  routes:
    multiplications:
      path: /multiplications/**
      url: http://localhost:8085/social-multiplication/multiplications
    results:
      path: /results/**
      url: http://localhost:8085//social-multiplication/results
    leaders:
      path: /leaders/**
      url: http://localhost:8089/gamification/leaders
    stats:
      path: /stats/**
      url: http://localhost:8089/gamification/stats

endpoints:
  trace:
    sensitive: false

ribbon:
  eureka:
    enabled: false