server:
  port: 8080
  servlet:
    contextPath: /social-multiplication

spring:
  datasource:
    url: jdbc:postgresql://192.168.1.180:30010/social_multiplication_db
    username: social_multiplication
    password: social_multiplication
    driverClassName: org.postgresql.Driver
    hikari:
      minimumIdle: 1
      idleTimeout: 120000
      maximumPoolSize: 2
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        temp:
          use_jdbc_metadata_defaults: false
