FROM nginx:alpine
##Environment para settar o timezone
ENV TZ=America/Sao_Paulo
## Copy our default nginx config
COPY ./nginx/default.conf  /etc/nginx/conf.d/default.conf
## Remove default nginx website
RUN rm -rf /usr/share/nginx/html/*
## From ‘builder’ stage copy over the artifacts in dist folder to default nginx public folder
COPY ./codes /usr/share/nginx/html/@nomeSource@
##download do pack de timezone e ajuste para a zona certa
RUN apk update
RUN apk add tzdata
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime
RUN echo $TZ > /etc/timezone
EXPOSE @exposePort@
CMD ["nginx", "-g", "daemon off;"]
