---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      expose: "true"
      provider: accesstage
      project: @nomeSource@
      version: @versionGulp@
      group: com.accesstage
    name: @nomeSource@
  spec:
    ports:
    - nodePort: @nodePort@
      port: @exposePort@
      protocol: TCP
      targetPort: @exposePort@
    selector:
      project: @nomeSource@
      provider: accesstage
      group: com.accesstage
    type: NodePort
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      provider: accesstage
      project: @nomeSource@
      version: @versionGulp@
      group: com.accesstage
    name: @nomeSource@
  spec:
    replicas: 1
    selector:
      matchLabels:
        project: @nomeSource@
        provider: accesstage
        version: @versionGulp@
        group: com.accesstage
    template:
      metadata:
        labels:
          provider: accesstage
          project: @nomeSource@
          version: @versionGulp@
          group: com.accesstage
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: @registry@/@nomeSource@:@versionGulp@
          imagePullPolicy: Always
          name: @nomeSource@
          securityContext:
            privileged: false